# Template trainer

# training settings
batch_size: 4
max_epochs: 1000
optim_name: sgd
optim_lr: 0.01
reg_weight: 0.00003
val_every: 50
lrschedule: warmup_cosine
warmup_epochs: 10
# seed: 3487
seed: 42
iter_per_epoch: 250
train_by_iter: True
deep_supervision: True
save_checkpoint: True
