dataset_name: flare
data_dir: /pathto/data/FLARE2022

crop_nums: 4
in_channels: 1
out_channels: 14
space_x: 1.5
space_y: 1.5
space_z: 2.0
roi_x: 96 # prev 96
roi_y: 96 # prev 96
roi_z: 96 # prev 96

# workers: 4